### ISSUE TITLE
BetterMessageLinks could not be compiled

### ISSUE THREAD

**Issue by SierraKomodo** [TheGreenPig/BetterDiscordPlugins#21]
BetterMessageLinks fails to compile in the current version of BetterDiscord.

**Comment by MetaNite64** [comment]
Can confirm on my end as well; here's the console output that BD provided upon attempting a reload (i.e. I redownloaded a fresh copy of the plugin file):
```
TypeError: Cannot read property 'default' of undefined
    at eval (betterdiscord://plugins/BetterMessageLinks.plugin.js:182:57)
    at eval (betterdiscord://plugins/BetterMessageLinks.plugin.js:692:3)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at Object.reloadAddon (<anonymous>:4:10053)
    at AsyncFunction.<anonymous> (<anonymous>:4:7189)
```

**Comment by dragonunitedtm** [comment]
same here.

**Comment by Ecconia** [comment]
Same stacktrace for me (slightly different entry point by BD, but else same), version `1.4.12`

**Comment by M0REKZ** [comment]
same

**Comment by B-Nerd** [comment]
same problem it happened after the big better discord update that said this will break plugins so @TheGreenPig  please fix
this is the compile error
TypeError: Cannot read property 'default' of undefined
    at eval (betterdiscord://plugins/BetterMessageLinks.plugin.js:182:57)
    at eval (betterdiscord://plugins/BetterMessageLinks.plugin.js:692:3)
    at Object.requireAddon (<anonymous>:4:37112)
    at Object.loadAddon (<anonymous>:4:8234)
    at Object.loadAddon (<anonymous>:4:34784)
    at Object.loadAllAddons (<anonymous>:4:10708)
    at Object.initialize (<anonymous>:4:5130)
    at Object.initialize (<anonymous>:4:33979)
    at Object.startup (<anonymous>:4:390667)

**Comment by revelcw** [comment]
+1 Still broken for me, @TheGreenPig please fix soon!

**Comment by rollingmoai** [comment]
~Now fixed, please close the issue~

**Comment by pmcintyre3** [comment]
It is not fixed for me. Installed the latest BD and tried to install via Plugin Repo.   


![image](https://user-images.githubusercontent.com/2632059/212985765-f78e8863-22ef-4440-ae5f-3717b7b00925.png)

**Comment by B-Nerd** [comment]
it is fixed download it manually

**Comment by rollingmoai** [comment]
@TheGreenPig broken again
