### ISSUE TITLE
better message links does not compile

### ISSUE THREAD

**Issue by B-Nerd** [TheGreenPig/BetterDiscordPlugins#25]
here is the error log it happens on the last better discord update
ADDON ERRORS
Plugins
BetterBannedUsers
Could not be compiled. See console for details.
BetterMessageLinks
Could not be compiled. See console for details.
TypeError: Cannot read property 'Type' of undefined
    at eval (betterdiscord://plugins/BetterMessageLinks.plugin.js:192:45)
    at eval (betterdiscord://plugins/BetterMessageLinks.plugin.js:692:3)
    at Object.requireAddon (<anonymous>:4:37112)
    at Object.loadAddon (<anonymous>:4:8234)
    at Object.loadAddon (<anonymous>:4:34784)
    at Object.loadAllAddons (<anonymous>:4:10708)
    at Object.initialize (<anonymous>:4:5130)
    at Object.initialize (<anonymous>:4:33979)
    at Object.startup (<anonymous>:4:390667)

**Comment by Capy369** [comment]
Me too!

**Comment by dantdmdarealguy** [comment]
same here

**Comment by firingthoughts** [comment]
same here
